/* eslint-disable */

export enum OpCodes {
    OP_Unknown = 'OP_Unknown',
    OP_LoginWeb = 'OP_LoginWeb',
    OP_LoginAccepted = 'OP_LoginAccepted',
    OP_PlayEverquestRequest = 'OP_PlayEverquestRequest',
    OP_PlayEverquestResponse = 'OP_PlayEverquestResponse',
    OP_ServerListRequest = 'OP_ServerListRequest',
    OP_ServerListResponse = 'OP_ServerListResponse',
    OP_SendLoginInfo = 'OP_SendLoginInfo',
    OP_WebInitiateConnection = 'OP_WebInitiateConnection',
    OP_SendCharInfo = 'OP_SendCharInfo',
    Nested_WorldServer = 'Nested_WorldServer',
    Nested_CharacterSelectEntry = 'Nested_CharacterSelectEntry',
    Nested_CharSelectEquip = 'Nested_CharSelectEquip',
    Nested_Tint = 'Nested_Tint',
    OP_ExploreUnknown = 'OP_ExploreUnknown',
    OP_0x0193 = 'OP_0x0193',
    OP_0x0347 = 'OP_0x0347',
    OP_AAAction = 'OP_AAAction',
    OP_AAExpUpdate = 'OP_AAExpUpdate',
    OP_AcceptNewTask = 'OP_AcceptNewTask',
    OP_AckPacket = 'OP_AckPacket',
    OP_Action = 'OP_Action',
    OP_Action2 = 'OP_Action2',
    OP_AddNimbusEffect = 'OP_AddNimbusEffect',
    OP_AdventureData = 'OP_AdventureData',
    OP_AdventureDetails = 'OP_AdventureDetails',
    OP_AdventureFinish = 'OP_AdventureFinish',
    OP_AdventureInfo = 'OP_AdventureInfo',
    OP_AdventureInfoRequest = 'OP_AdventureInfoRequest',
    OP_AdventureLeaderboardReply = 'OP_AdventureLeaderboardReply',
    OP_AdventureLeaderboardRequest = 'OP_AdventureLeaderboardRequest',
    OP_AdventureMerchantPurchase = 'OP_AdventureMerchantPurchase',
    OP_AdventureMerchantRequest = 'OP_AdventureMerchantRequest',
    OP_AdventureMerchantResponse = 'OP_AdventureMerchantResponse',
    OP_AdventureMerchantSell = 'OP_AdventureMerchantSell',
    OP_AdventurePointsUpdate = 'OP_AdventurePointsUpdate',
    OP_AdventureRequest = 'OP_AdventureRequest',
    OP_AdventureStatsReply = 'OP_AdventureStatsReply',
    OP_AdventureStatsRequest = 'OP_AdventureStatsRequest',
    OP_AdventureUpdate = 'OP_AdventureUpdate',
    OP_AggroMeterLockTarget = 'OP_AggroMeterLockTarget',
    OP_AggroMeterTargetInfo = 'OP_AggroMeterTargetInfo',
    OP_AggroMeterUpdate = 'OP_AggroMeterUpdate',
    OP_AltCurrency = 'OP_AltCurrency',
    OP_AltCurrencyMerchantReply = 'OP_AltCurrencyMerchantReply',
    OP_AltCurrencyMerchantRequest = 'OP_AltCurrencyMerchantRequest',
    OP_AltCurrencyPurchase = 'OP_AltCurrencyPurchase',
    OP_AltCurrencyReclaim = 'OP_AltCurrencyReclaim',
    OP_AltCurrencySell = 'OP_AltCurrencySell',
    OP_AltCurrencySellSelection = 'OP_AltCurrencySellSelection',
    OP_Animation = 'OP_Animation',
    OP_AnnoyingZoneUnknown = 'OP_AnnoyingZoneUnknown',
    OP_ApplyPoison = 'OP_ApplyPoison',
    OP_ApproveName = 'OP_ApproveName',
    OP_ApproveWorld = 'OP_ApproveWorld',
    OP_ApproveZone = 'OP_ApproveZone',
    OP_Assist = 'OP_Assist',
    OP_AssistGroup = 'OP_AssistGroup',
    OP_AugmentInfo = 'OP_AugmentInfo',
    OP_AugmentItem = 'OP_AugmentItem',
    OP_AutoAttack = 'OP_AutoAttack',
    OP_AutoAttack2 = 'OP_AutoAttack2',
    OP_AutoFire = 'OP_AutoFire',
    OP_Bandolier = 'OP_Bandolier',
    OP_BankerChange = 'OP_BankerChange',
    OP_Barter = 'OP_Barter',
    OP_Bazaar = 'OP_Bazaar',
    OP_BazaarInspect = 'OP_BazaarInspect',
    OP_BazaarSearch = 'OP_BazaarSearch',
    OP_BecomeCorpse = 'OP_BecomeCorpse',
    OP_BecomeTrader = 'OP_BecomeTrader',
    OP_Begging = 'OP_Begging',
    OP_BeginCast = 'OP_BeginCast',
    OP_Bind_Wound = 'OP_Bind_Wound',
    OP_BlockedBuffs = 'OP_BlockedBuffs',
    OP_BoardBoat = 'OP_BoardBoat',
    OP_BookButton = 'OP_BookButton',
    OP_Buff = 'OP_Buff',
    OP_BuffCreate = 'OP_BuffCreate',
    OP_BuffRemoveRequest = 'OP_BuffRemoveRequest',
    OP_Bug = 'OP_Bug',
    OP_CameraEffect = 'OP_CameraEffect',
    OP_Camp = 'OP_Camp',
    OP_CancelSneakHide = 'OP_CancelSneakHide',
    OP_CancelTask = 'OP_CancelTask',
    OP_CancelTrade = 'OP_CancelTrade',
    OP_CashReward = 'OP_CashReward',
    OP_CastSpell = 'OP_CastSpell',
    OP_ChangeSize = 'OP_ChangeSize',
    OP_ChannelMessage = 'OP_ChannelMessage',
    OP_CharacterCreate = 'OP_CharacterCreate',
    OP_CharacterCreateRequest = 'OP_CharacterCreateRequest',
    OP_CharInventory = 'OP_CharInventory',
    OP_Charm = 'OP_Charm',
    OP_ChatMessage = 'OP_ChatMessage',
    OP_ClearAA = 'OP_ClearAA',
    OP_ClearBlockedBuffs = 'OP_ClearBlockedBuffs',
    OP_ClearLeadershipAbilities = 'OP_ClearLeadershipAbilities',
    OP_ClearNPCMarks = 'OP_ClearNPCMarks',
    OP_ClearObject = 'OP_ClearObject',
    OP_ClearSurname = 'OP_ClearSurname',
    OP_ClickDoor = 'OP_ClickDoor',
    OP_ClickObject = 'OP_ClickObject',
    OP_ClickObjectAction = 'OP_ClickObjectAction',
    OP_ClientError = 'OP_ClientError',
    OP_ClientReady = 'OP_ClientReady',
    OP_ClientTimeStamp = 'OP_ClientTimeStamp',
    OP_ClientUpdate = 'OP_ClientUpdate',
    OP_CloseContainer = 'OP_CloseContainer',
    OP_CloseTributeMaster = 'OP_CloseTributeMaster',
    OP_ColoredText = 'OP_ColoredText',
    OP_CombatAbility = 'OP_CombatAbility',
    OP_Command = 'OP_Command',
    OP_CompletedTasks = 'OP_CompletedTasks',
    OP_ConfirmDelete = 'OP_ConfirmDelete',
    OP_Consent = 'OP_Consent',
    OP_ConsentDeny = 'OP_ConsentDeny',
    OP_ConsentResponse = 'OP_ConsentResponse',
    OP_Consider = 'OP_Consider',
    OP_ConsiderCorpse = 'OP_ConsiderCorpse',
    OP_Consume = 'OP_Consume',
    OP_ControlBoat = 'OP_ControlBoat',
    OP_CorpseDrag = 'OP_CorpseDrag',
    OP_CorpseDrop = 'OP_CorpseDrop',
    OP_CrashDump = 'OP_CrashDump',
    OP_CrystalCountUpdate = 'OP_CrystalCountUpdate',
    OP_CrystalCreate = 'OP_CrystalCreate',
    OP_CrystalReclaim = 'OP_CrystalReclaim',
    OP_CustomTitles = 'OP_CustomTitles',
    OP_Damage = 'OP_Damage',
    OP_Death = 'OP_Death',
    OP_DelegateAbility = 'OP_DelegateAbility',
    OP_DeleteCharacter = 'OP_DeleteCharacter',
    OP_DeleteCharge = 'OP_DeleteCharge',
    OP_DeleteItem = 'OP_DeleteItem',
    OP_DeletePetition = 'OP_DeletePetition',
    OP_DeleteSpawn = 'OP_DeleteSpawn',
    OP_DeleteSpell = 'OP_DeleteSpell',
    OP_DenyResponse = 'OP_DenyResponse',
    OP_Disarm = 'OP_Disarm',
    OP_DisarmTraps = 'OP_DisarmTraps',
    OP_DisciplineTimer = 'OP_DisciplineTimer',
    OP_DisciplineUpdate = 'OP_DisciplineUpdate',
    OP_DiscordMerchantInventory = 'OP_DiscordMerchantInventory',
    OP_DoGroupLeadershipAbility = 'OP_DoGroupLeadershipAbility',
    OP_DuelDecline = 'OP_DuelDecline',
    OP_DuelAccept = 'OP_DuelAccept',
    OP_DumpName = 'OP_DumpName',
    OP_Dye = 'OP_Dye',
    OP_DynamicWall = 'OP_DynamicWall',
    OP_DzAddPlayer = 'OP_DzAddPlayer',
    OP_DzChooseZone = 'OP_DzChooseZone',
    OP_DzChooseZoneReply = 'OP_DzChooseZoneReply',
    OP_DzCompass = 'OP_DzCompass',
    OP_DzExpeditionEndsWarning = 'OP_DzExpeditionEndsWarning',
    OP_DzExpeditionInfo = 'OP_DzExpeditionInfo',
    OP_DzExpeditionInvite = 'OP_DzExpeditionInvite',
    OP_DzExpeditionInviteResponse = 'OP_DzExpeditionInviteResponse',
    OP_DzExpeditionLockoutTimers = 'OP_DzExpeditionLockoutTimers',
    OP_DzListTimers = 'OP_DzListTimers',
    OP_DzMakeLeader = 'OP_DzMakeLeader',
    OP_DzMemberList = 'OP_DzMemberList',
    OP_DzMemberListName = 'OP_DzMemberListName',
    OP_DzMemberListStatus = 'OP_DzMemberListStatus',
    OP_DzPlayerList = 'OP_DzPlayerList',
    OP_DzQuit = 'OP_DzQuit',
    OP_DzRemovePlayer = 'OP_DzRemovePlayer',
    OP_DzSetLeaderName = 'OP_DzSetLeaderName',
    OP_DzSwapPlayer = 'OP_DzSwapPlayer',
    OP_Emote = 'OP_Emote',
    OP_EndLootRequest = 'OP_EndLootRequest',
    OP_EnduranceUpdate = 'OP_EnduranceUpdate',
    OP_EnterChat = 'OP_EnterChat',
    OP_EnterWorld = 'OP_EnterWorld',
    OP_EnvDamage = 'OP_EnvDamage',
    OP_ExpansionInfo = 'OP_ExpansionInfo',
    OP_ExpUpdate = 'OP_ExpUpdate',
    OP_FaceChange = 'OP_FaceChange',
    OP_Feedback = 'OP_Feedback',
    OP_FeignDeath = 'OP_FeignDeath',
    OP_FellowshipUpdate = 'OP_FellowshipUpdate',
    OP_FindPersonReply = 'OP_FindPersonReply',
    OP_FindPersonRequest = 'OP_FindPersonRequest',
    OP_FinishTrade = 'OP_FinishTrade',
    OP_FinishWindow = 'OP_FinishWindow',
    OP_FinishWindow2 = 'OP_FinishWindow2',
    OP_Fishing = 'OP_Fishing',
    OP_Fling = 'OP_Fling',
    OP_FloatListThing = 'OP_FloatListThing',
    OP_Forage = 'OP_Forage',
    OP_ForceFindPerson = 'OP_ForceFindPerson',
    OP_FormattedMessage = 'OP_FormattedMessage',
    OP_FriendsWho = 'OP_FriendsWho',
    OP_GetGuildMOTD = 'OP_GetGuildMOTD',
    OP_GetGuildMOTDReply = 'OP_GetGuildMOTDReply',
    OP_GetGuildsList = 'OP_GetGuildsList',
    OP_GiveMoney = 'OP_GiveMoney',
    OP_GMApproval = 'OP_GMApproval',
    OP_GMBecomeNPC = 'OP_GMBecomeNPC',
    OP_GMDelCorpse = 'OP_GMDelCorpse',
    OP_GMEmoteZone = 'OP_GMEmoteZone',
    OP_GMEndTraining = 'OP_GMEndTraining',
    OP_GMEndTrainingResponse = 'OP_GMEndTrainingResponse',
    OP_GMFind = 'OP_GMFind',
    OP_GMGoto = 'OP_GMGoto',
    OP_GMHideMe = 'OP_GMHideMe',
    OP_GMKick = 'OP_GMKick',
    OP_GMKill = 'OP_GMKill',
    OP_GMLastName = 'OP_GMLastName',
    OP_GMNameChange = 'OP_GMNameChange',
    OP_GMSearchCorpse = 'OP_GMSearchCorpse',
    OP_GMServers = 'OP_GMServers',
    OP_GMSummon = 'OP_GMSummon',
    OP_GMToggle = 'OP_GMToggle',
    OP_GMTraining = 'OP_GMTraining',
    OP_GMTrainSkill = 'OP_GMTrainSkill',
    OP_GMTrainSkillConfirm = 'OP_GMTrainSkillConfirm',
    OP_GMZoneRequest = 'OP_GMZoneRequest',
    OP_GMZoneRequest2 = 'OP_GMZoneRequest2',
    OP_GroundSpawn = 'OP_GroundSpawn',
    OP_GroupAcknowledge = 'OP_GroupAcknowledge',
    OP_GroupCancelInvite = 'OP_GroupCancelInvite',
    OP_GroupDelete = 'OP_GroupDelete',
    OP_GroupDisband = 'OP_GroupDisband',
    OP_GroupDisbandOther = 'OP_GroupDisbandOther',
    OP_GroupDisbandYou = 'OP_GroupDisbandYou',
    OP_GroupFollow = 'OP_GroupFollow',
    OP_GroupFollow2 = 'OP_GroupFollow2',
    OP_GroupInvite = 'OP_GroupInvite',
    OP_GroupInvite2 = 'OP_GroupInvite2',
    OP_GroupLeaderChange = 'OP_GroupLeaderChange',
    OP_GroupLeadershipAAUpdate = 'OP_GroupLeadershipAAUpdate',
    OP_GroupMakeLeader = 'OP_GroupMakeLeader',
    OP_GroupMentor = 'OP_GroupMentor',
    OP_GroupRoles = 'OP_GroupRoles',
    OP_GroupUpdate = 'OP_GroupUpdate',
    OP_GroupUpdateB = 'OP_GroupUpdateB',
    OP_GroupUpdateLeaderAA = 'OP_GroupUpdateLeaderAA',
    OP_GuildBank = 'OP_GuildBank',
    OP_GuildBankItemList = 'OP_GuildBankItemList',
    OP_GuildCreate = 'OP_GuildCreate',
    OP_GuildDelete = 'OP_GuildDelete',
    OP_GuildDemote = 'OP_GuildDemote',
    OP_GuildInvite = 'OP_GuildInvite',
    OP_GuildInviteAccept = 'OP_GuildInviteAccept',
    OP_GuildLeader = 'OP_GuildLeader',
    OP_GuildManageAdd = 'OP_GuildManageAdd',
    OP_GuildManageBanker = 'OP_GuildManageBanker',
    OP_GuildManageRemove = 'OP_GuildManageRemove',
    OP_GuildManageStatus = 'OP_GuildManageStatus',
    OP_GuildMemberLevelUpdate = 'OP_GuildMemberLevelUpdate',
    OP_GuildMemberList = 'OP_GuildMemberList',
    OP_GuildMemberUpdate = 'OP_GuildMemberUpdate',
    OP_GuildMOTD = 'OP_GuildMOTD',
    OP_GuildPeace = 'OP_GuildPeace',
    OP_GuildPromote = 'OP_GuildPromote',
    OP_GuildPublicNote = 'OP_GuildPublicNote',
    OP_GuildRemove = 'OP_GuildRemove',
    OP_GuildsList = 'OP_GuildsList',
    OP_GuildStatus = 'OP_GuildStatus',
    OP_GuildTributeInfo = 'OP_GuildTributeInfo',
    OP_GuildUpdateURLAndChannel = 'OP_GuildUpdateURLAndChannel',
    OP_GuildWar = 'OP_GuildWar',
    OP_Heartbeat = 'OP_Heartbeat',
    OP_Hide = 'OP_Hide',
    OP_HideCorpse = 'OP_HideCorpse',
    OP_HPUpdate = 'OP_HPUpdate',
    OP_Illusion = 'OP_Illusion',
    OP_IncreaseStats = 'OP_IncreaseStats',
    OP_InitialHPUpdate = 'OP_InitialHPUpdate',
    OP_InitialMobHealth = 'OP_InitialMobHealth',
    OP_InspectAnswer = 'OP_InspectAnswer',
    OP_InspectBuffs = 'OP_InspectBuffs',
    OP_InspectMessageUpdate = 'OP_InspectMessageUpdate',
    OP_InspectRequest = 'OP_InspectRequest',
    OP_InstillDoubt = 'OP_InstillDoubt',
    OP_InterruptCast = 'OP_InterruptCast',
    OP_ItemLinkClick = 'OP_ItemLinkClick',
    OP_ItemLinkResponse = 'OP_ItemLinkResponse',
    OP_ItemLinkText = 'OP_ItemLinkText',
    OP_ItemName = 'OP_ItemName',
    OP_ItemPacket = 'OP_ItemPacket',
    OP_ItemPreview = 'OP_ItemPreview',
    OP_ItemRecastDelay = 'OP_ItemRecastDelay',
    OP_ItemVerifyReply = 'OP_ItemVerifyReply',
    OP_ItemVerifyRequest = 'OP_ItemVerifyRequest',
    OP_ItemViewUnknown = 'OP_ItemViewUnknown',
    OP_Jump = 'OP_Jump',
    OP_KeyRing = 'OP_KeyRing',
    OP_KickPlayers = 'OP_KickPlayers',
    OP_KnowledgeBase = 'OP_KnowledgeBase',
    OP_LDoNButton = 'OP_LDoNButton',
    OP_LDoNDisarmTraps = 'OP_LDoNDisarmTraps',
    OP_LDoNInspect = 'OP_LDoNInspect',
    OP_LDoNOpen = 'OP_LDoNOpen',
    OP_LDoNPickLock = 'OP_LDoNPickLock',
    OP_LDoNSenseTraps = 'OP_LDoNSenseTraps',
    OP_LeadershipExpToggle = 'OP_LeadershipExpToggle',
    OP_LeadershipExpUpdate = 'OP_LeadershipExpUpdate',
    OP_LeaveAdventure = 'OP_LeaveAdventure',
    OP_LeaveBoat = 'OP_LeaveBoat',
    OP_LevelAppearance = 'OP_LevelAppearance',
    OP_LevelUpdate = 'OP_LevelUpdate',
    OP_LFGAppearance = 'OP_LFGAppearance',
    OP_LFGCommand = 'OP_LFGCommand',
    OP_LFGGetMatchesRequest = 'OP_LFGGetMatchesRequest',
    OP_LFGGetMatchesResponse = 'OP_LFGGetMatchesResponse',
    OP_LFGResponse = 'OP_LFGResponse',
    OP_LFGuild = 'OP_LFGuild',
    OP_LFPCommand = 'OP_LFPCommand',
    OP_LFPGetMatchesRequest = 'OP_LFPGetMatchesRequest',
    OP_LFPGetMatchesResponse = 'OP_LFPGetMatchesResponse',
    OP_LinkedReuse = 'OP_LinkedReuse',
    OP_LoadSpellSet = 'OP_LoadSpellSet',
    OP_LocInfo = 'OP_LocInfo',
    OP_LockoutTimerInfo = 'OP_LockoutTimerInfo',
    OP_Login = 'OP_Login',
    OP_LoginComplete = 'OP_LoginComplete',
    OP_LoginExpansionPacketData = 'OP_LoginExpansionPacketData',
    OP_LoginUnknown1 = 'OP_LoginUnknown1',
    OP_LoginUnknown2 = 'OP_LoginUnknown2',
    OP_Logout = 'OP_Logout',
    OP_LogoutReply = 'OP_LogoutReply',
    OP_LogServer = 'OP_LogServer',
    OP_LootComplete = 'OP_LootComplete',
    OP_LootItem = 'OP_LootItem',
    OP_LootRequest = 'OP_LootRequest',
    OP_ManaChange = 'OP_ManaChange',
    OP_ManaUpdate = 'OP_ManaUpdate',
    OP_MarkNPC = 'OP_MarkNPC',
    OP_MarkRaidNPC = 'OP_MarkRaidNPC',
    OP_Marquee = 'OP_Marquee',
    OP_MemorizeSpell = 'OP_MemorizeSpell',
    OP_Mend = 'OP_Mend',
    OP_MendHPUpdate = 'OP_MendHPUpdate',
    OP_MercenaryAssign = 'OP_MercenaryAssign',
    OP_MercenaryCommand = 'OP_MercenaryCommand',
    OP_MercenaryDataRequest = 'OP_MercenaryDataRequest',
    OP_MercenaryDataResponse = 'OP_MercenaryDataResponse',
    OP_MercenaryDataUpdate = 'OP_MercenaryDataUpdate',
    OP_MercenaryDataUpdateRequest = 'OP_MercenaryDataUpdateRequest',
    OP_MercenaryDismiss = 'OP_MercenaryDismiss',
    OP_MercenaryHire = 'OP_MercenaryHire',
    OP_MercenarySuspendRequest = 'OP_MercenarySuspendRequest',
    OP_MercenarySuspendResponse = 'OP_MercenarySuspendResponse',
    OP_MercenaryTimer = 'OP_MercenaryTimer',
    OP_MercenaryTimerRequest = 'OP_MercenaryTimerRequest',
    OP_MercenaryUnknown1 = 'OP_MercenaryUnknown1',
    OP_MercenaryUnsuspendResponse = 'OP_MercenaryUnsuspendResponse',
    OP_MobEnduranceUpdate = 'OP_MobEnduranceUpdate',
    OP_MobHealth = 'OP_MobHealth',
    OP_MobManaUpdate = 'OP_MobManaUpdate',
    OP_MobRename = 'OP_MobRename',
    OP_MobUpdate = 'OP_MobUpdate',
    OP_MoneyOnCorpse = 'OP_MoneyOnCorpse',
    OP_MoneyUpdate = 'OP_MoneyUpdate',
    OP_MOTD = 'OP_MOTD',
    OP_MoveCoin = 'OP_MoveCoin',
    OP_MoveDoor = 'OP_MoveDoor',
    OP_MoveItem = 'OP_MoveItem',
    OP_MoveMultipleItems = 'OP_MoveMultipleItems',
    OP_MoveLogDisregard = 'OP_MoveLogDisregard',
    OP_MoveLogRequest = 'OP_MoveLogRequest',
    OP_MultiLineMsg = 'OP_MultiLineMsg',
    OP_NewSpawn = 'OP_NewSpawn',
    OP_NewTitlesAvailable = 'OP_NewTitlesAvailable',
    OP_NewZone = 'OP_NewZone',
    OP_OnLevelMessage = 'OP_OnLevelMessage',
    OP_OpenContainer = 'OP_OpenContainer',
    OP_OpenDiscordMerchant = 'OP_OpenDiscordMerchant',
    OP_OpenGuildTributeMaster = 'OP_OpenGuildTributeMaster',
    OP_OpenInventory = 'OP_OpenInventory',
    OP_OpenTributeMaster = 'OP_OpenTributeMaster',
    OP_PDeletePetition = 'OP_PDeletePetition',
    OP_PetBuffWindow = 'OP_PetBuffWindow',
    OP_PetCommands = 'OP_PetCommands',
    OP_PetCommandState = 'OP_PetCommandState',
    OP_PetHoTT = 'OP_PetHoTT',
    OP_Petition = 'OP_Petition',
    OP_PetitionBug = 'OP_PetitionBug',
    OP_PetitionCheckIn = 'OP_PetitionCheckIn',
    OP_PetitionCheckout = 'OP_PetitionCheckout',
    OP_PetitionCheckout2 = 'OP_PetitionCheckout2',
    OP_PetitionDelete = 'OP_PetitionDelete',
    OP_PetitionQue = 'OP_PetitionQue',
    OP_PetitionRefresh = 'OP_PetitionRefresh',
    OP_PetitionResolve = 'OP_PetitionResolve',
    OP_PetitionSearch = 'OP_PetitionSearch',
    OP_PetitionSearchResults = 'OP_PetitionSearchResults',
    OP_PetitionSearchText = 'OP_PetitionSearchText',
    OP_PetitionUnCheckout = 'OP_PetitionUnCheckout',
    OP_PetitionUpdate = 'OP_PetitionUpdate',
    OP_PickPocket = 'OP_PickPocket',
    OP_PlayerProfile = 'OP_PlayerProfile',
    OP_PlayerStateAdd = 'OP_PlayerStateAdd',
    OP_PlayerStateRemove = 'OP_PlayerStateRemove',
    OP_PlayMP3 = 'OP_PlayMP3',
    OP_Poll = 'OP_Poll',
    OP_PollResponse = 'OP_PollResponse',
    OP_PopupResponse = 'OP_PopupResponse',
    OP_PostEnterWorld = 'OP_PostEnterWorld',
    OP_PotionBelt = 'OP_PotionBelt',
    OP_PreLogoutReply = 'OP_PreLogoutReply',
    OP_PurchaseLeadershipAA = 'OP_PurchaseLeadershipAA',
    OP_PVPLeaderBoardDetailsReply = 'OP_PVPLeaderBoardDetailsReply',
    OP_PVPLeaderBoardDetailsRequest = 'OP_PVPLeaderBoardDetailsRequest',
    OP_PVPLeaderBoardReply = 'OP_PVPLeaderBoardReply',
    OP_PVPLeaderBoardRequest = 'OP_PVPLeaderBoardRequest',
    OP_PVPStats = 'OP_PVPStats',
    OP_QueryResponseThing = 'OP_QueryResponseThing',
    OP_QueryUCSServerStatus = 'OP_QueryUCSServerStatus',
    OP_RaidDelegateAbility = 'OP_RaidDelegateAbility',
    OP_RaidClearNPCMarks = 'OP_RaidClearNPCMarks',
    OP_RaidInvite = 'OP_RaidInvite',
    OP_RaidJoin = 'OP_RaidJoin',
    OP_RaidUpdate = 'OP_RaidUpdate',
    OP_RandomNameGenerator = 'OP_RandomNameGenerator',
    OP_RandomReply = 'OP_RandomReply',
    OP_RandomReq = 'OP_RandomReq',
    OP_ReadBook = 'OP_ReadBook',
    OP_RecipeAutoCombine = 'OP_RecipeAutoCombine',
    OP_RecipeDetails = 'OP_RecipeDetails',
    OP_RecipeReply = 'OP_RecipeReply',
    OP_RecipesFavorite = 'OP_RecipesFavorite',
    OP_RecipesSearch = 'OP_RecipesSearch',
    OP_ReclaimCrystals = 'OP_ReclaimCrystals',
    OP_ReloadUI = 'OP_ReloadUI',
    OP_RemoveAllDoors = 'OP_RemoveAllDoors',
    OP_RemoveBlockedBuffs = 'OP_RemoveBlockedBuffs',
    OP_RemoveNimbusEffect = 'OP_RemoveNimbusEffect',
    OP_RemoveTrap = 'OP_RemoveTrap',
    OP_Report = 'OP_Report',
    OP_ReqClientSpawn = 'OP_ReqClientSpawn',
    OP_ReqNewZone = 'OP_ReqNewZone',
    OP_RequestClientZoneChange = 'OP_RequestClientZoneChange',
    OP_RequestDuel = 'OP_RequestDuel',
    OP_RequestKnowledgeBase = 'OP_RequestKnowledgeBase',
    OP_RequestTitles = 'OP_RequestTitles',
    OP_RespawnWindow = 'OP_RespawnWindow',
    OP_RespondAA = 'OP_RespondAA',
    OP_RestState = 'OP_RestState',
    OP_Rewind = 'OP_Rewind',
    OP_RezzAnswer = 'OP_RezzAnswer',
    OP_RezzComplete = 'OP_RezzComplete',
    OP_RezzRequest = 'OP_RezzRequest',
    OP_Sacrifice = 'OP_Sacrifice',
    OP_SafeFallSuccess = 'OP_SafeFallSuccess',
    OP_SafePoint = 'OP_SafePoint',
    OP_Save = 'OP_Save',
    OP_SaveOnZoneReq = 'OP_SaveOnZoneReq',
    OP_SelectTribute = 'OP_SelectTribute',
    OP_SendAAStats = 'OP_SendAAStats',
    OP_SendAATable = 'OP_SendAATable',
    OP_SendExpZonein = 'OP_SendExpZonein',
    OP_SendFindableNPCs = 'OP_SendFindableNPCs',
    OP_SendGuildTributes = 'OP_SendGuildTributes',
    OP_SendMaxCharacters = 'OP_SendMaxCharacters',
    OP_SendMembership = 'OP_SendMembership',
    OP_SendMembershipDetails = 'OP_SendMembershipDetails',
    OP_SendSystemStats = 'OP_SendSystemStats',
    OP_SendTitleList = 'OP_SendTitleList',
    OP_SendTributes = 'OP_SendTributes',
    OP_SendZonepoints = 'OP_SendZonepoints',
    OP_SenseHeading = 'OP_SenseHeading',
    OP_SenseTraps = 'OP_SenseTraps',
    OP_SessionReady = 'OP_SessionReady',
    OP_SetChatServer = 'OP_SetChatServer',
    OP_SetChatServer2 = 'OP_SetChatServer2',
    OP_SetFace = 'OP_SetFace',
    OP_SetGroupTarget = 'OP_SetGroupTarget',
    OP_SetGuildMOTD = 'OP_SetGuildMOTD',
    OP_SetGuildRank = 'OP_SetGuildRank',
    OP_SetRunMode = 'OP_SetRunMode',
    OP_SetServerFilter = 'OP_SetServerFilter',
    OP_SetStartCity = 'OP_SetStartCity',
    OP_SetTitle = 'OP_SetTitle',
    OP_SetTitleReply = 'OP_SetTitleReply',
    OP_SharedTaskMemberList = 'OP_SharedTaskMemberList',
    OP_SharedTaskAddPlayer = 'OP_SharedTaskAddPlayer',
    OP_SharedTaskRemovePlayer = 'OP_SharedTaskRemovePlayer',
    OP_SharedTaskMakeLeader = 'OP_SharedTaskMakeLeader',
    OP_SharedTaskMemberInvite = 'OP_SharedTaskMemberInvite',
    OP_SharedTaskInvite = 'OP_SharedTaskInvite',
    OP_SharedTaskInviteResponse = 'OP_SharedTaskInviteResponse',
    OP_SharedTaskAcceptNew = 'OP_SharedTaskAcceptNew',
    OP_SharedTaskMemberChange = 'OP_SharedTaskMemberChange',
    OP_SharedTaskPlayerList = 'OP_SharedTaskPlayerList',
    OP_SharedTaskSelectWindow = 'OP_SharedTaskSelectWindow',
    OP_SharedTaskQuit = 'OP_SharedTaskQuit',
    OP_TaskTimers = 'OP_TaskTimers',
    OP_Shielding = 'OP_Shielding',
    OP_ShopDelItem = 'OP_ShopDelItem',
    OP_ShopEnd = 'OP_ShopEnd',
    OP_ShopEndConfirm = 'OP_ShopEndConfirm',
    OP_ShopItem = 'OP_ShopItem',
    OP_ShopPlayerBuy = 'OP_ShopPlayerBuy',
    OP_ShopPlayerSell = 'OP_ShopPlayerSell',
    OP_ShopRequest = 'OP_ShopRequest',
    OP_SimpleMessage = 'OP_SimpleMessage',
    OP_SkillUpdate = 'OP_SkillUpdate',
    OP_Sneak = 'OP_Sneak',
    OP_Some3ByteHPUpdate = 'OP_Some3ByteHPUpdate',
    OP_Some6ByteHPUpdate = 'OP_Some6ByteHPUpdate',
    OP_SomeItemPacketMaybe = 'OP_SomeItemPacketMaybe',
    OP_Sound = 'OP_Sound',
    OP_SpawnAppearance = 'OP_SpawnAppearance',
    OP_SpawnDoor = 'OP_SpawnDoor',
    OP_SpawnPositionUpdate = 'OP_SpawnPositionUpdate',
    OP_SpecialMesg = 'OP_SpecialMesg',
    OP_SpellEffect = 'OP_SpellEffect',
    OP_Split = 'OP_Split',
    OP_Stamina = 'OP_Stamina',
    OP_Stun = 'OP_Stun',
    OP_Surname = 'OP_Surname',
    OP_SwapSpell = 'OP_SwapSpell',
    OP_TargetBuffs = 'OP_TargetBuffs',
    OP_TargetCommand = 'OP_TargetCommand',
    OP_TargetHoTT = 'OP_TargetHoTT',
    OP_TargetMouse = 'OP_TargetMouse',
    OP_TargetReject = 'OP_TargetReject',
    OP_TaskActivity = 'OP_TaskActivity',
    OP_TaskActivityComplete = 'OP_TaskActivityComplete',
    OP_TaskDescription = 'OP_TaskDescription',
    OP_TaskHistoryReply = 'OP_TaskHistoryReply',
    OP_TaskHistoryRequest = 'OP_TaskHistoryRequest',
    OP_TaskRequestTimer = 'OP_TaskRequestTimer',
    OP_TaskSelectWindow = 'OP_TaskSelectWindow',
    OP_Taunt = 'OP_Taunt',
    OP_TestBuff = 'OP_TestBuff',
    OP_TGB = 'OP_TGB',
    OP_TimeOfDay = 'OP_TimeOfDay',
    OP_Track = 'OP_Track',
    OP_TrackTarget = 'OP_TrackTarget',
    OP_TrackUnknown = 'OP_TrackUnknown',
    OP_TradeAcceptClick = 'OP_TradeAcceptClick',
    OP_TradeBusy = 'OP_TradeBusy',
    OP_TradeCoins = 'OP_TradeCoins',
    OP_TradeMoneyUpdate = 'OP_TradeMoneyUpdate',
    OP_Trader = 'OP_Trader',
    OP_TraderBuy = 'OP_TraderBuy',
    OP_TraderDelItem = 'OP_TraderDelItem',
    OP_TradeRequest = 'OP_TradeRequest',
    OP_TradeRequestAck = 'OP_TradeRequestAck',
    OP_TraderItemUpdate = 'OP_TraderItemUpdate',
    OP_TraderShop = 'OP_TraderShop',
    OP_TradeSkillCombine = 'OP_TradeSkillCombine',
    OP_Translocate = 'OP_Translocate',
    OP_TributeInfo = 'OP_TributeInfo',
    OP_TributeItem = 'OP_TributeItem',
    OP_TributeMoney = 'OP_TributeMoney',
    OP_TributeNPC = 'OP_TributeNPC',
    OP_TributePointUpdate = 'OP_TributePointUpdate',
    OP_TributeTimer = 'OP_TributeTimer',
    OP_TributeToggle = 'OP_TributeToggle',
    OP_TributeUpdate = 'OP_TributeUpdate',
    OP_Untargetable = 'OP_Untargetable',
    OP_UpdateAA = 'OP_UpdateAA',
    OP_UpdateAura = 'OP_UpdateAura',
    OP_UpdateLeadershipAA = 'OP_UpdateLeadershipAA',
    OP_VetClaimReply = 'OP_VetClaimReply',
    OP_VetClaimRequest = 'OP_VetClaimRequest',
    OP_VetRewardsAvaliable = 'OP_VetRewardsAvaliable',
    OP_VoiceMacroIn = 'OP_VoiceMacroIn',
    OP_VoiceMacroOut = 'OP_VoiceMacroOut',
    OP_WeaponEquip1 = 'OP_WeaponEquip1',
    OP_WearChange = 'OP_WearChange',
    OP_Weather = 'OP_Weather',
    OP_Weblink = 'OP_Weblink',
    OP_WhoAllRequest = 'OP_WhoAllRequest',
    OP_WhoAllResponse = 'OP_WhoAllResponse',
    OP_World_Client_CRC1 = 'OP_World_Client_CRC1',
    OP_World_Client_CRC2 = 'OP_World_Client_CRC2',
    OP_World_Client_CRC3 = 'OP_World_Client_CRC3',
    OP_WorldClientReady = 'OP_WorldClientReady',
    OP_WorldComplete = 'OP_WorldComplete',
    OP_WorldLogout = 'OP_WorldLogout',
    OP_WorldObjectsSent = 'OP_WorldObjectsSent',
    OP_WorldUnknown001 = 'OP_WorldUnknown001',
    OP_XTargetAutoAddHaters = 'OP_XTargetAutoAddHaters',
    OP_XTargetOpen = 'OP_XTargetOpen',
    OP_XTargetOpenResponse = 'OP_XTargetOpenResponse',
    OP_XTargetRequest = 'OP_XTargetRequest',
    OP_XTargetResponse = 'OP_XTargetResponse',
    OP_YellForHelp = 'OP_YellForHelp',
    OP_ZoneChange = 'OP_ZoneChange',
    OP_ZoneComplete = 'OP_ZoneComplete',
    OP_ZoneEntry = 'OP_ZoneEntry',
    OP_ZoneGuildList = 'OP_ZoneGuildList',
    OP_ZoneInUnknown = 'OP_ZoneInUnknown',
    OP_ZonePlayerToBind = 'OP_ZonePlayerToBind',
    OP_ZoneServerInfo = 'OP_ZoneServerInfo',
    OP_ZoneServerReady = 'OP_ZoneServerReady',
    OP_ZoneSpawns = 'OP_ZoneSpawns',
    OP_ZoneUnavail = 'OP_ZoneUnavail',
    OP_ResetAA = 'OP_ResetAA',
    OP_UnderWorld = 'OP_UnderWorld',
}

// Login
export interface LoginMessage {
    username?: string;
    password?: string;
}

export interface LoginReply {
    key?: string;
    errorStrId?: number;
    failedAttempts?: number;
    lsid?: number;
    success?: boolean;
    showPlayerCount?: boolean;
}

export interface LoginRequest {
    sequence?: number;
}

export interface WorldServer {
    ip?: string;
    serverType?: number;
    serverId?: number;
    longName?: string;
    countryCode?: string;
    languageCode?: string;
    status?: number;
    playersOnline?: number;
}

export interface LoginServerResponse {
    serverCount?: number;
    servers?: WorldServer[];
}

export interface PlayEverquest {
    serverId?: number;
}

export interface PlayEverquestResponse {
    serverId?: number;
    success?: boolean;
    errorStrId?: number;
}

// World
export interface WebInitiateConnection {
    login?: boolean;
}

export interface LoginInfo {
    name?: string;
    password?: string;
    zoning?: number;
}

export interface Tint {
    blue?: number;
    green?: number;
    red?: number;
    useTint?: number;
}

export interface CharSelectEquip {
    material?: number;
    color?: Tint;
}

export interface CharacterSelectEntry {
    name?: string;
    charClass?: number;
    race?: number;
    level?: number;
    zone?: number;
    instance?: number;
    gender?: number;
    face?: number;
    equip?: CharSelectEquip[];
    deity?: number;
    primaryIdFile?: number;
    secondaryIdFile?: number;
    goHome?: number;
    enabled?: number;
    lastLogin?: number;
}

export interface CharacterSelect {
    characterCount?: number;
    characters?: CharacterSelectEntry[];
}
